host = "0.0.0.0"
port = 3000
max_file_size = "200MiB"
database_url = "sqlite://./data/clipchan.db?mode=rwc"
tmp_dir = "./data/temp"

[storage]
type = "local" # "local" or "s3"
[storage.local]
path = "./data/clips"

#[storage.s3]
#endpoint = "https://s3.us-west-2.amazonaws.com"
#bucket = "clipchan"
#region = "us-west-2"
#access_key = "your_access_key_id"
#secret_key = "your_secret_key"

[stream]
buffer_time = 15 # seconds

video_height = 1080
video_width = 1920
video_framerate = 60
video_bitrate = 4000 # 4000 kbps
video_speed = "faster"

audio_sample_format = "S16LE"
audio_rate = 44100
audio_channels = 2
audio_bitrate = 128000 # 128 kbps
title_font = "Arial 20"
title_halign = "right"
title_valign = "top"

