host = "127.0.0.1"
port = 3000
max_file_size = "200MiB"
database_url = "sqlite://./data/clipchan.db?mode=rwc"
tmp_dir = "./data/temp"

[storage.local]
path = "data/clips"

[stream]
video_height = 1080
video_width = 1920
video_framerate = 60
video_bitrate = 4000 # 4000 kbps
video_speed = "faster"

audio_sample_format = "S16LE"
audio_rate = 44100
audio_channels = 2
audio_bitrate = 128000 # 128 kbps
title_font = "Arial 20"
title_halign = "right"
title_valign = "top"

